# -*- coding: utf-8 -*-
"""complete_fashion_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORa_s9cEXJKl3PXlWD6vpIWqbHBo53Q4
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from tensorflow.keras.applications.xception import Xception
from tensorflow.keras.applications.xception import preprocess_input
from tensorflow.keras.applications.xception import decode_predictions

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split

from tensorflow.keras import mixed_precision

learning_rate = 0.001
input_size = 299
n_count = 256
dropout = 0.4

!git clone https://github.com/alexeygrigorev/clothing-dataset

df = pd.read_csv("./clothing-dataset/images.csv")

df.head()

df["image"] = df.image + ".jpg"
df.label = df.label.str.lower().str.replace(" ", "_")
df = df.dropna(subset=["label"])
df = df[~df["label"].isin(["not_sure", "skip"])]

classes = sorted(df.label.unique())

def prepare_paths_and_labels(df, directory):

    file_paths = directory + "/" + df["image"].astype(str)
    labels = pd.get_dummies(df["label"]).reindex(columns=classes, fill_value=0).values

    return file_paths, labels

train_df, tmp_test_df = train_test_split(df, test_size = 0.4, random_state = 1, stratify = df.label)
test_df, val_df = train_test_split(tmp_test_df, test_size = 0.5, random_state = 1, stratify = tmp_test_df.label)

df.head()

train_paths, train_labels = prepare_paths_and_labels(train_df, "./clothing-dataset/images")
val_paths,   val_labels   = prepare_paths_and_labels(val_df,   "./clothing-dataset/images")
test_paths,  test_labels  = prepare_paths_and_labels(test_df,  "./clothing-dataset/images")

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(factor=15.0 / 360.0),
    layers.RandomTranslation(height_factor = 0.1, width_factor = 0.1)
])

def load_and_preprocess_image(path, label):
    image = tf.io.read_file(path)
    image = tf.io.decode_image(image, channels=3, expand_animations=False)
    image = tf.image.resize(image, [299, 299])

    image = preprocess_input(image)

    return image, label

BATCH_SIZE = 128
AUTOTUNE = tf.data.AUTOTUNE

def create_dataset(paths, labels, is_training=False):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    if is_training:
        ds = ds.shuffle(buffer_size=len(paths))

    ds = ds.map(load_and_preprocess_image, num_parallel_calls=AUTOTUNE)
    ds = ds.cache()

    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(buffer_size=AUTOTUNE)

    return ds

train_ds = create_dataset(train_paths, train_labels, is_training=True)

val_ds = create_dataset(val_paths, val_labels, is_training=False)
test_ds = create_dataset(test_paths, test_labels, is_training=False)

def make_model(input_size, learning_rate, neuron_count, dropout):

    base_model = Xception(
        weights = "imagenet",
        include_top = False,
        input_shape = (input_size, input_size, 3)
    )

    base_model.trainable = False

    inputs = keras.Input(shape = (input_size, input_size, 3))
    x = data_augmentation(inputs)

    base = base_model(x, training = False)

    vectors = keras.layers.GlobalAveragePooling2D()(base)
    inner = keras.layers.Dense(neuron_count, activation = "relu")(vectors)
    drop = keras.layers.Dropout(dropout)(inner)
    outputs = keras.layers.Dense(18)(drop)

    model = keras.Model(inputs, outputs)

    optimizer = keras.optimizers.Adam(learning_rate = learning_rate)
    loss = keras.losses.CategoricalCrossentropy(from_logits = True)

    model.compile(
        optimizer = optimizer,
        loss = loss,
        metrics = ["accuracy"]
    )

    return model

mixed_precision.set_global_policy('mixed_float16')

checkpoint = keras.callbacks.ModelCheckpoint(
    "xception_v6_{epoch:02d}_{val_accuracy:.3f}.h5",
    save_best_only = True,
    monitor = "val_accuracy",
    mode = "max"
)
model = make_model(input_size, learning_rate, n_count, dropout)
history = model.fit(train_ds, epochs = 50, validation_data = val_ds, callbacks=[checkpoint])

import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

!nvidia-smi

